### ISSUE TITLE
We need a footprint for the DPDT relays

### ISSUE THREAD

**Issue by felipesanches** [portalmod/mod-kicad-footprints#2]
Crudo,
please, provide me the technical datasheet of the selected component so that I can create the KiCAD footprint for it.

**Comment by ricardocrudo** [comment]
Let's use the same family of the previous relay. The part number for DPDT is IM03TS. Following are the links to digikey and documentations:
http://www.digikey.com/product-search/en?KeyWords=IM03TS&WT.z_header=search_go
http://www.mouser.com/catalog/catalogusd/647/2043.pdf
http://www.mouser.com/ds/2/418/ENG_SS_108-98001_S%5B1%5D-205061.pdf

**Comment by felipesanches** [comment]
I just figured out that we already have a footprint for the IM03TS component in this repository, so I am using it in the PCB layout.
